"""One-off: brings README.md and CLAUDE.md in line with the rebuilt front page and its bottles (29 Sep 2026).
Exact-match edits; fails on a second run."""
ROOT = r"C:\Users\malha\Desktop\Webapps\perfume-profiler"


def edit(rel, pairs):
    p = ROOT + "\\" + rel
    s = open(p, encoding="utf-8").read()
    for a, b in pairs:
        assert s.count(a) == 1, (rel, a[:80])
        s = s.replace(a, b)
    open(p, "w", encoding="utf-8", newline="\n").write(s)


readme = open(ROOT + r"\README.md", encoding="utf-8").read()
old_index = [l for l in readme.split("\n") if l.startswith("| `site/index.html` |")][0]
old_lp = [l for l in readme.split("\n") if l.startswith("| `site/js/landing.js` |")][0]
old_ld = [l for l in readme.split("\n") if l.startswith("| `site/js/landing-data.js` |")][0]
old_bl = [l for l in readme.split("\n") if l.startswith("| `tools/build_landing.js` |")][0]
edit("README.md", [
    (old_index, "| `site/index.html` | The front page, for a visitor who scrolls more than reads. A hook about the bottle you bought and stopped using; the real bottle of one of the quiz's twenty perfumes, which sprays straight up into its listed notes by stage and gives way to another perfume's bottle on the next press, with the quiz's first question under it (tried it? A yes goes into every link to the quiz as `?tried=`); an example result from a real run of the quiz; three sections of one tap each (the 1,000-perfume test, counted as the quiz rules out; a perfume box turned round to its ingredient label; a 100-person grid per smell on a plum band); the quiz's four parts and the articles. Each section's sources are folded under it; the writing is centred. Markup and the scripts `js/landing.js` and the generated `js/landing-data.js`; styles `landing.css` on top of `site.css`. |"),
    ("| `site/landing.css` | The front page's styles: an arched alcove of cream glass for the atomizer, the palette widened with the nine palate groups' colours and a plum for the bulb. |",
     "| `site/landing.css` | The front page's styles: an arched alcove of cream glass where the bottle stands on a table, the palette widened with the nine palate groups' colours and a plum for the band in the middle of the page. |"),
    (old_lp, "| `site/js/landing.js` | The front page: its words in both languages, the bottle on the stage (its picture from `img/hero/`, a canvas mist from the top of its glass, the notes rising in three rows, the next bottle swapped in on a press) and the tried-it question, the example result, the 1,000-perfume test, the box and its label, the grid of noses; the funnel's `reach:start` and `land:tried`. Everything that moves sits under reduced-motion: no-preference. |"),
    ("| `site/js/bottle3d.js` | The front page's atomizer drawn live with three.js: an engraved flacon of antique brass with a jewel that takes each perfume's colour, a braided cord, a netted bulb that squeezes, a tassel. Draws on demand, never in a loop; without WebGL the still picture stays. |\n", ""),
    ("| `site/img/atomizer-ltr.webp`, `atomizer-rtl.webp` | The atomizer's still pictures, drawn from `js/bottle3d.js` by `tools/render_atomizer.py`: the first paint, and the fallback without WebGL. |",
     "| `site/img/hero/` | The front page's large bottle pictures, one per quiz bottle, cut out and trimmed by `tools/fetch_hero_bottles.py`. Never edited by hand. |"),
    (old_ld, "| `site/js/landing-data.js` | Generated by `tools/build_landing.js`: the twenty quiz bottles with their notes by stage, family and palate group and their large pictures' sizes and spray points, every family's description and count, the palate groups' colours, the 1,000-perfume test's counts, the box's label, and the example result. Never edited by hand. |"),
    (old_bl, "| `tools/build_landing.js` | Writes `site/js/landing-data.js` from `data.js`, `mapper.js`, `bottles.js`, `materials.js`, `engine.js` (the test counts as the quiz rules out), the palate groups in `quiz.js`, the labels in `evidence/labels/`, `reference/images/hero.json`, and a run of the quiz in the test stub for the example result; `tests/landing.test.js` fails while it is out of date. |"),
    ("| `tools/render_atomizer.py` | Draws the atomizer's two still pictures from `site/js/bottle3d.js` in headless Chromium and checks that the nozzle and bulb fall where `landing.js` expects them. Run after any change to the 3D atomizer. |",
     "| `tools/fetch_hero_bottles.py` | Makes the front page's large bottle pictures in `site/img/hero/` from the catalogue photo's source or Fragrantica's larger pictures, whichever stands taller; records each one's size and spray point in `reference/images/hero.json` and draws `build/hero_sheet.png` for checking. Needs Pillow; run `node tools/build_landing.js` after. |"),
])
edit("CLAUDE.md", [
    ("""  `js/quiz.js` the quiz (`quiz.html`), with `js/motion.js` its motion and touch (screen transitions, in-place
  updates, the dock), and `js/landing.js` the front page (`index.html`), with `js/bottle3d.js` its 3D atomizer (three.js
  from jsDelivr, pinned by the import map in `index.html`; `python tools/render_atomizer.py` redraws its still pictures); `js/evidence.js`, `js/bottles.js` and""",
     """  `js/quiz.js` the quiz (`quiz.html`), with `js/motion.js` its motion and touch (screen transitions, in-place
  updates, the dock), and `js/landing.js` the front page (`index.html`), whose large bottle pictures in `img/hero/` come
  from `python tools/fetch_hero_bottles.py`; `js/evidence.js`, `js/bottles.js` and"""),
])
print("applied")
