#!/usr/bin/env node
/* Builds evidence.js, the provenance layers above the curated catalogue.

   Layers (round table, reference/debate/ROUNDTABLE.md): curated (data.js) < notes (vendor pyramid
   through the mapper) < label (ingredient list through materials.js) < book (quoted literature).
   The page merges them at load; higher layer wins per family and stage; every tag remembers its
   source. This script:
     1. reads evidence/applied_changes.jsonl and turns every change whose source is a book
        or the Guide into a book-layer entry (weight, quote, source, confidence);
     2. reads evidence/labels/*.txt (one pasted ingredient list per file; first lines are
        "id:", "market:", "date:", "code:", "url:" then the list) and turns each into a label-layer
        entry through materials.js;
     3. writes site/js/evidence.js.
   It does not touch data.js. Run after every audit or label addition; tests/ fails while the file is
   out of date. */

const fs = require("fs");
const path = require("path");
const { ROOT, SITE, loadSite } = require("./lib/site");
const OUT = path.join(SITE, "js", "evidence.js");

function build() {
  const w = loadSite("data", "materials");
  const ids = new Set(w.PP_DATA.PERFUMES.map(p => p.id));
  const fams = new Set(Object.keys(w.PP_DATA.FAMILIES));

  /* 1. book layer from the audit changelog (guide and chemistry sources only) */
  const book = {};
  const logPath = path.join(ROOT, "evidence", "applied_changes.jsonl");
  if (fs.existsSync(logPath)) {
    for (const line of fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean)) {
      const c = JSON.parse(line);
      if (!["guide", "chemistry"].includes(c.source)) continue;
      if (!ids.has(c.id) || !fams.has(c.family)) continue;
      book[c.id] = book[c.id] || { opening: {}, heart: {}, drydown: {} };
      book[c.id][c.stage][c.family] = { w: Number(c.to), quote: c.quote || "", source: c.source === "guide" ? "Turin and Sanchez, Perfumes: The Guide 2018" : "Ohloff, Pickenhagen, Kraft and Grau, Scent and Chemistry (2022)", confidence: c.confidence, reason: c.reason || "" };
    }
  }

  /* 2. label layer from pasted ingredient lists */
  const label = {};
  const labelsDir = path.join(ROOT, "evidence", "labels");
  let labelCount = 0, rejected = [];
  if (fs.existsSync(labelsDir)) {
    const seenLists = new Map();
    for (const f of fs.readdirSync(labelsDir).filter(x => x.endsWith(".txt")).sort()) {
      const text = fs.readFileSync(path.join(labelsDir, f), "utf8");
      const meta = {}; const body = [];
      for (const line of text.split("\n")) {
        const m = line.match(/^(id|market|date|code|url|source):\s*(.*)$/i);
        if (m) meta[m[1].toLowerCase()] = m[2].trim(); else body.push(line);
      }
      const list = body.join("\n").trim();
      if (!meta.id || !ids.has(meta.id)) { rejected.push(f + ": unknown id"); continue; }
      /* reject copy-pasted lists: the same list on two different perfumes tells us nothing */
      const key = w.PP_MATERIALS.norm(list);
      if (seenLists.has(key) && seenLists.get(key) !== meta.id) { rejected.push(f + ": identical to " + seenLists.get(key)); continue; }
      seenLists.set(key, meta.id);
      const parsed = w.PP_MATERIALS.parse(list);
      if (parsed.materialsDeclared < 3) { rejected.push(f + ": fewer than three materials"); continue; }
      label[meta.id] = { market: meta.market || "", date: meta.date || "", code: meta.code || "", url: meta.url || "", format: parsed.format, stages: parsed.stages, presence: parsed.presence, absent: parsed.absent, materials: parsed.items.filter(i => !i.ignored).map(i => ({ raw: i.raw, material: i.material, index: i.index })), unmatched: parsed.unmatched };
      labelCount++;
    }
  }

  const text = `/* Generated by tools/build_evidence.js. Do not edit by hand: add labels under evidence/labels/ and rerun.
   book: quoted literature per id, stage and family. label: parsed ingredient lists per id. */
window.PP_EVIDENCE = ${JSON.stringify({ built: new Date().toISOString().slice(0, 10), book, label }, null, 1)};
`;
  return { text, bookCount: Object.keys(book).length, labelCount, rejected };
}

if (require.main === module) {
  const r = build();
  fs.writeFileSync(OUT, r.text);
  console.log(`site/js/evidence.js written: book entries ${r.bookCount}, label entries ${r.labelCount}${r.rejected.length ? "; rejected: " + r.rejected.join("; ") : ""}`);
}

module.exports = { build, OUT };
